### PR TITLE
Typos and wording around "imporance" and "key carbinet"

### PR DESCRIPTION
**Pull request by barthon-b**
Correcting _imporance_ to _impor**t**ance_ and replacing _key carbinet_ with _locked chest_. _Carbinet_ was probably meant to be _cabinet_ originally, _key_ possibly indicating some sort of a lock but the word cabinet is not typically used for the item we see on the screen, which is clearly a chest (see [this](https://en.wikipedia.org/wiki/Chest_(furniture)) wiki article). Following this logic I allowed myself to update the wording around to make it clearer that the chest is locked and that the player needs a _key_ rather than the original phrasing of a _password_.

Note, the invalid spelling of _carbinet_ exists in other translations but I was not confident enough to update the other translations. Just as in English there is typically a couple of words a particular language has for various containers.

### CODE REVIEW

**Comment by blindpirate** [comment]
Thanks for the PR. Typically you just need to correct the English version and delete other language versions, we'll generate the translations from Google API. I'll take care of it so no actions required on your side. 

Note: you are supposed to get coin/reputation reward (There should be a robot commenting in this PR saying "hey, thanks for the contribution, you will get X coin and Y reputation") for contributing, but unfortunately this system is not finished yet. Good news is that the PR is still here so in the future we'll definitely revisit these PRs and give you rewards.

Thanks again.

**Comment by barthon-b** [comment]
Thank you for your effort and for considering my PR, @blindpirate !

I see that the PR is now merged but just one question in case I raise any PRs in the future:

> just need to correct the English version and delete other language versions

Based on the example of this PR, can you indicate which file I should have modified and which lines I should have removed? I don't want to generate more work for you with future PRs! :-)

EDIT:
OK, so after reviewing the [internationalization page](https://github.com/ByteLegend/ByteLegend/blob/master/docs/en/i18n.md#add-a-new-language), I think I shouldn't be touching the json files and focus on updating the YAML ones only. Is this correct?

**Comment by gtn1024** [comment]
> Thank you for your effort and for considering my PR, @blindpirate !
> 
> I see that the PR is now merged but just one question in case I raise any PRs in the future:
> 
> > just need to correct the English version and delete other language versions
> 
> Based on the example of this PR, can you indicate which file I should have modified and which lines I should have removed? I don't want to generate more work for you with future PRs! :-)
> 
> EDIT: OK, so after reviewing the [internationalization page](https://github.com/ByteLegend/ByteLegend/blob/master/docs/en/i18n.md#add-a-new-language), I think I shouldn't be touching the json files and focus on updating the YAML ones only. Is this correct?

Right, you do not need to take care of `i18n-auto.json` as it is generated automatically.

**Comment by blindpirate** [comment]
> Based on the example of this PR, can you indicate which file I should have modified and which lines I should have removed? I don't want to generate more work for you with future PRs! :-)

`*-auto.json` is generated by automation tool, it can even be totally deleted. The reason why it exists is to cache the translation result and save Google translation API quota. So for future PRs: edit the YAML and delete the entry of all languages in the JSON.

**Pull request merged**
